version: '3.9'

services:
  # nodetest:
  #   image: nodetest
  #   build:
  #     context: .
  #     dockerfile: 
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 8080:8080
  # mysql:
  #   image: mysql:8.0.26
  #   platform: linux/amd64
  #   build: ./docket-mysql
  #   ports:
  #     - 3306:3306
  db:
    image: mysql:8.0
    container_name: DBmysql
    platform: linux/amd64
    restart: always
    ports:
           - '3306:3306'
    environment:
           MYSQL_ROOT_PASSWORD: helloworld
    volumes: 
           - ./db:/var/lib/mysql
    networks:
      - mysql  
   
  phpadmin:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    restart: always
    ports:
     - '8001:80'
    networks:
     - mysql
    environment:
     PMA_HOST: db 
   
  node:
    depends_on:
      - db
      - phpadmin
    links:
      - db  
    image: node:16-alpine3.14
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - HOST=db     
    ports:
      - 8080:8080
    networks:
      - mysql
volumes: 
    db:     
networks:
  mysql:
    driver: bridge     
  